# List of biomes to ignore (Registry names)
IgnoredBiomes=minecraft:river,minecraft:frozen_river,minecraft:beach,minecraft:snowy_beach,minecraft:stony_shore,minecraft:mushroom_fields,minecraft:ice_spikes

# Enable keyword-based biome detection?
EnableKeywordDetection=true
# List for all of the biomes to be enabled or not: 
EnableCaves=true
EnableDripstoneCaves=true
EnableOcean=true
EnableForest=true
EnableDarkForest=true
EnableSnowy=true
EnableDesert=true
EnableNether=true
EnableEnd=true
EnableDefault=true
